# config.yam
# 一言设置
yiyan: true
# 疯狂星期四设置
KFC: true
# 网易云热评设置
wyyrp: true
# 天气查询设置
tianqi: true
# 歌词类设置
geci: true
# 唱鸭设置
changya: true
# 随机表情包设置
sjbqb: true
# 攻受短文设置
gsdw: true
# ping 地址设置
ping: true
# 谁艾特我设置
shuianwo: true
# 垃圾分类设置
ljfl: true
# 随机动漫图设置
sjdmt: true
# 哔哩哔哩热搜榜设置
bilihot: true
# 知乎热搜榜设置
zhihuhot: true
# 抖音热搜榜设置
douyinhot: true
# 今日头条热搜榜设置
toutiaohot: true
# 今日头条热点新闻设置
toutiaohotnew: true
# 生成二维码设置
qrcode: true
# 头像设置
qqtx: true
# 群头像设置
qqqtx: true
# 举牌设置
jupai: true
# 网页截图设置
wyjt: true
# 哔哩哔哩解析设置
bilitv: true
# 更新推送设置
UpdateTask: true
